"""Self-contained HTML report: opens straight from disk, with no server and no external assets."""

from __future__ import annotations

import base64
import html
import io
from collections import Counter

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

CSS = """
body{font:15px/1.5 system-ui,-apple-system,Segoe UI,sans-serif;max-width:860px;margin:32px auto;padding:0 16px;color:#1d232b;background:#fff}
h1{font-size:22px;margin:0 0 4px} h2{font-size:16px;margin:28px 0 8px}
.muted{color:#5b6573} table{border-collapse:collapse;width:100%} td,th{border-bottom:1px solid #e3e7ec;padding:6px 8px;text-align:left}
th{font-weight:600;width:45%} .status{display:inline-block;padding:2px 10px;border-radius:12px;font-weight:600;font-size:13px}
.succeeded{background:#e3f4e8;color:#17693a} .failed,.cancelled{background:#fbe7e6;color:#9b2c24}
.error{background:#fbe7e6;border-left:4px solid #c0392b;padding:10px 12px;white-space:pre-wrap;font-family:ui-monospace,monospace;font-size:13px}
img{max-width:100%;border:1px solid #e3e7ec;border-radius:6px}
"""


def _umap_png(coords: list, groups: list | None) -> str:
    xy = list(zip(*coords))
    fig, ax = plt.subplots(figsize=(6.4, 5.2), dpi=110)
    if groups:
        for g in sorted(set(groups)):
            idx = [i for i, v in enumerate(groups) if v == g]
            ax.scatter([xy[0][i] for i in idx], [xy[1][i] for i in idx], s=4, label=g, alpha=0.8, linewidths=0)
        ax.legend(markerscale=3, fontsize=8, frameon=False, loc="center left", bbox_to_anchor=(1, 0.5))
    else:
        ax.scatter(xy[0], xy[1], s=4, color="#3a6ea5", alpha=0.8, linewidths=0)
    ax.set_xlabel("UMAP 1")
    ax.set_ylabel("UMAP 2")
    ax.set_xticks([])
    ax.set_yticks([])
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    fig.tight_layout()
    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    plt.close(fig)
    return base64.b64encode(buf.getvalue()).decode()


def _rows(pairs) -> str:
    return "".join(f"<tr><th>{html.escape(str(k))}</th><td>{html.escape(str(v))}</td></tr>" for k, v in pairs)


def render(state: dict, params: dict, metrics: dict | None = None, error: str | None = None, sample_col: str | None = None) -> str:
    status = state.get("status", "unknown")
    m = metrics or {}
    qc = [
        ("cells before QC", m.get("n_cells_before", "-")),
        ("cells after QC", m.get("n_cells_after_qc", "-")),
        ("genes", m.get("n_genes", "-")),
        ("mean genes per cell (kept)", m.get("mean_genes_per_cell", "-")),
        ("median mito % (kept)", m.get("median_pct_mito", "-")),
    ]
    if m.get("groups"):
        qc += [(f"{sample_col} = {g}", f"{n} cells") for g, n in sorted(Counter(m["groups"]).items())]

    if m.get("umap"):
        fig = f'<img alt="UMAP" src="data:image/png;base64,{_umap_png(m["umap"], m.get("groups"))}">'
    else:
        fig = '<p class="muted">No embedding (job failed).</p>' if status != "succeeded" else '<p class="muted">No embedding.</p>'

    err = f'<h2>Error</h2><div class="error">{html.escape(error)}</div>' if error else ""
    times = " → ".join(t for t in (state.get("started_at"), state.get("ended_at")) if t)
    used = list(params.items()) + ([("sample_col", sample_col)] if sample_col else [])
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>pipeboard report {html.escape(state.get('id', ''))}</title><style>{CSS}</style></head>
<body>
<h1>pipeboard report</h1>
<p class="muted">job <code>{html.escape(state.get('id', ''))}</code> · <span class="status {html.escape(status)}">{html.escape(status)}</span> · {html.escape(times)}</p>
{err}
<h2>Parameters</h2><table>{_rows(used)}</table>
<h2>QC</h2><table>{_rows(qc)}</table>
<h2>UMAP</h2>{fig}
<p class="muted" style="margin-top:32px">Generated by pipeboard on public 10x PBMC3k data.</p>
</body></html>
"""
